spring:
  application:
    name: api-gateway

  security:
    oauth2:
      client:
        registration:
          client-app:
            client-id: client-app
            client-secret: admin123
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,read,write
        provider:
          client-app: # Este ID debe coincidir con el registration ID
            issuer-uri: http://localhost:8083

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
        # Podés agregar más rutas si es necesario
        # - id: other-service
        #   uri: lb://other-service
        #   predicates:
        #     - Path=/api/v1/other/**
