server:
  port: 8080

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      client:
        registration:
          client-app:
            provider: custom-provider
            client-id: client-app
            client-secret: admin123
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, read, write
        provider:
          custom-provider:
            issuer-uri: http://security-service:8083
      resourceserver:
        jwt:
          issuer-uri: http://security-service:8083

    cloud:
      gateway:
        default-filters:
          - TokenRelay
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/v1/user/**
        # Puedes agregar más rutas aquí si es necesario

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE

      # Podés agregar más rutas si es necesario
      # - id: other-service
      #   uri: lb://other-service
      #   predicates:
      #     - Path=/api/v1/other/**

      # Podés agregar más rutas si es necesario
        # - id: other-service
        #   uri: lb://other-service
        #   predicates:
        #     - Path=/api/v1/other/**
