server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**