server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://registry-service:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: false
    hostname: user-service

management:
  tracing:
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

spring:
  cloud:
    discovery:
      enabled: true
      #data:
      # mongodb:
      #  host: localhost
      # port: 27017
      # database: company
      # username: company
      # password: password

#  thread-pool-bulkhead:
#    instances:
#      departmentService:
#        maxThreadPoolSize: 1
#        coreThreadPoolSize: 1
#        queueCapacity: 1